# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HkPG7Bf73yU8BTLt7W6eN3DumWlf-pXL
"""

!pip install nltk

import nltk
from nltk.tokenize import word_tokenize

nltk.download('all')

text = "Hello World. This is a test."

tokens = word_tokenize(text)

print("Tokens:",tokens)

text = "Hello, World"

upper_text=text.upper()

print("Uppercase text:",upper_text)

text = "Hello, World"

lower_text=text.lower()

print("Lowercase text:",lower_text)

import string
import re

text = "Hello,world! How is it going? #python"

cleand_text = re.sub(r'[^\w\s]','',text)

print("Cleaned text:",cleand_text)

from nltk.corpus import stopwords

text = "This is an example sentence with some stop words."

words=text.split()

stop_word=set(stopwords.words('english'))

filtered_words=[word for word in words if word.lower() not in stop_word]

filtered_text=' '.join(filtered_words)

print("Filtered Text:",filtered_text)

from nltk.stem import PorterStemmer

word=["running","happier","better","dogs","jumping","easiliy"]

stemmer=PorterStemmer()

stemmed_words=[stemmer.stem(word) for word in word]

print("Stemmed words:",stemmed_words)

